version: '3.9'

services:
  db:
    image: mysql:8.4.3
    container_name: my-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123!@#
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user123!@#
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/db/my-mysql/data:/var/lib/mysql
      - ~/db/my-mysql/files:/var/lib/mysql-files
      - ~/db/my-mysql/config:/etc/mysql/conf.d
      - ~/db/my-mysql/init:/docker-entrypoint-initdb.d